name: picbudget_app
description: "Smart Budgeting App"

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  action_slider: ^0.7.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.0
  lottie: ^3.2.0
  password_strength: ^0.2.0
  path: ^1.9.0
  photo_view: ^0.15.0
  string_extensions: ^0.7.3
  transitioned_indexed_stack: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1A1A1A"
  image: assets/images/splash.png
  android: true
  android_12:
    color: "#1A1A1A"
    image: assets/images/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"
  adaptive_icon_background: "#1a1a1a"
  adaptive_icon_foreground: "assets/images/splash.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/backgrounds/
    - assets/models/
    - assets/lotties/

flutter_gen:
  output: lib/core/assets/
